apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: my-minecraft-server:latest
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: minecraft-data
              mountPath: /app
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc 